# -*- coding: utf-8 -*-
"""10. 컬렉션 매서드.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WYzszMWQKPoism18GTZ7iqjEVxJ7PcMY
"""

# 리스트 컴프리헨션
# 세트 컴프리헨션
# 딕셔너리 컴프리헨션
li1 = [i + 1 for i in range(10)]
print(li1)

# 리스트에 값을 추가하는 법
# .append() : 맨 뒤에 값을 추가
li1.append(100)
print(li1)

li1.insert(4, 200)
print(li1)

li1.remove(200)
print(li1)

li1.insert(4,200)
li1.insert(8,200)
print(li1)

# 먼저 만나는 값을 삭제
li1.remove(200)
print(li1)

# len(): 길이를 확인하는 함수
li2 = [(i + 1) * 10 for i in range(76)]
print(li2)
print(len(li2))

for i in li2:
    print(i)

for i in range(len(li2)):
    print(i)

li3 = [1, 4, 8, 7, 6, 9, 3, 4, 5]
print(max(li3))
print(min(li3))
print(sum(li3))

li3.sort() # 오름차순
print(li3)
li3.sort(reverse=True) # 내림차순
print(li3)

print(li3.pop())
print(li3.pop(4))
print(li3)

# 1. 빈 리스트를 생성하고, 1부터 10까지 추가하기
li4 = [1, 2, 3, 4, 5, 6, 7, 8 , 9, 10]
# 리스트 컴프리헨션, 리스트 메서드

li5 = [i + 1 for i in range(10)]

li6 = []

for i in range(10):
    li6.append(i + 1)

print(li4)
print(li5)
print(li6)

# 5명의 학생의 점수를 받아서 전체 총합과 평균을 구하기
li7 = []
for i in range(5):
    score = int(input(f'{i + 1}번째 학생의 점수를 입력하세요'))
    li7.append(score)

print(li7)
print('총합 : ', sum(li7))
print('평균 : ', sum(li7) / len(li7))

# 튜플 메서드
# .count()
name = '홍길동', '김길동', '장독대'
print(name.count(''))
print(name.index('홍길동'))

# .index()
print(name.index('김길동'))

# 세트 메서드
s1 = {'사과', '참외', '멜론', '바나나', '딸기', '사과', '참외'}
s1.add('망고')
print(s1)

# .remove(값): 값을 삭제하는 메서드
s1.remove('바나나')
# s1.remove('바나나') 오류 발생
# s1.discard('바나나') 오류가 발생하지 않음

print(s1)
print(s1.pop())
print(s1.pop())
print(s1.pop())
print(s1.pop())
print(s1)

# 딕셔너리 메서드
countries = {'korea': '서울', 'japan': '도쿄', 'china': '베이징'}

print(countries.keys())
print(countries.values())
print(countries.items())

for i in countries.items():
    print(i)

print(countries['korea'])
# print(cities['USA']) 오류가 등장함
print('우리나라 수도: ' + countries.get('USA', "없음"))