# -*- coding: utf-8 -*-
"""13. 영역(scope).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HxF5Msh5twggJOc-kg_L1MF_arqDey2p
"""

value = 100

def change_value():
    global value
    value = 20

change_value()

print(value)

"""# 영역(scope)
1. 지역변수
- 함수 내부에서 선언된 변수이며, 함수에서만 사용이 가능하다

2. 전역변수
- 함수 밖에서 선언한 변수, 전역에서 사용이 가능하다

#global문
- global문을 사용하면 함수 안에서도 전역변수의 값을 수정할 수 있다.
"""

# 10분
# 회사의 회사원 3명
# employee 함수를 3개
# employee1, employee2, employee3
# 함수를 이용해서 수입들을 모두 전역변수에 추가해야 한다.
income = 0

def employee1():
    global income
    income += 1000

def employee2():
    global income
    income += 2000

def employee3():
    global income
    income += 5000

employee1()
employee2()
employee3()

print(income)