# -*- coding: utf-8 -*-
"""15. 모듈(module).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VyDXWG4nar1bdq-eaRAdD2KjjLdxpbjo

#모듈(module)이란?
- 함수, 클래스, 변수 등을 하나의 파일에 모아 놓은 코드의 집합
- 모듈을 사용하면 코드를 재사용하고, 코드의 구조를 더 효율적으로 관리가 가능
- 파이썬의 파일(.py)은 모듈이 될 수 있다.

##모듈의 사용
    import문
    ex)
        from 파일명 import *(asterlist)
        *는 모든 것을 의미한다.

    특정 함수만 import
        from 모듈 import 함수
        from 모듈 import 함수1, 함수2
"""

# 유튜브 영상 가져오기
# <iframe width="560" height="315" src="https://www.youtube.com/embed/0TNFb5zgpbg?si=bFBPHSHILjnCNdCA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
from IPython.display import YouTubeVideo
video_id = "0TNFb5zgpbg"

YouTubeVideo(video_id, width=400)

# 이미지
from IPython.display import Image
Image(url="https://cdn.dailyvet.co.kr/wp-content/uploads/2024/05/15231647/20240515ceva_experts4.jpg",
      width=500)

# 시간
import time
print("안녕하세요!")
time.sleep(10)
print("반갑습니다!")

import random
# 랜덤(난수)과 관련된 여러 함수를 모아놓은 모듈

# 1~45
# randint(a, b)
print(random.randint(1, 45))

# 로또 번호 6개
for i in range(6):
    print(f"{i+1}번째 번호: {random.randint(1, 45)}")

# random.choice()
# 한명 뽑기
li1 = ["길동", "보고", "순신", "준경", "문덕", "익점"]
print(random.choice(li1))

# random.sample()
# 여러개 뽑기
print(random.sample(li1, 3))

from datetime import datetime
import pytz

# 시간을 다루는 모듈
# UTC 협정시간
now = datetime.now()
print(now)

# 한국 시간대로 변경
korea_time = pytz.timezone('Asia/Seoul')
local_time = datetime.now(korea_time)
print(local_time)