# -*- coding: utf-8 -*-
"""16. 클래스(class).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mTaZdc-dmKApDoioce55qCGQ0tsqMCGW
"""

class Animal:

    #초기화 생성자
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def canSpeak(self):
        print("")

# 객체화 코드
rabbit = Animal("토토", 2)
dog = Animal("강아지", 10)

print(rabbit.name)
print(dog.name)

# 카페 클래스 만들기
# 대표메뉴, 가격, 브랜드(생성자로 초기화)
# 메서드, 저희 브랜드의 대표 메뉴는 ooo, 가격은 ooo원 입니다.

class Cafe:
    def __init__(self, menu, price, brand):
        self.menu = menu
        self.price = price
        self.brand = brand

    def introduce(self):
        print(f"저희 {self.brand}의 대표 메뉴는 {self.menu}, 가격은 {self.price}원 입니다.")

cafeA = Cafe("아메리카노", 3000, "스타벅스")
cafeA.introduce()

cafeB = Cafe("카페라떼", 4000, "커피빈")
cafeB.introduce()

# 마켓 클래스 생성
# 토마토 판매중, 토마토의 가격은 3000원
# def sell

# User1, User2, User3 클래스 생성
# 각각 사용자마다 다른 할인율을 가지고 있다
# User1 5%, User2 10%, User3 25%
# 각각 유저는  10_000원을 가지고 있으며
# 유저의 할인율을 적용받아 마켓에서 토마토를 구매 후 잔액을 출력

class Market:
    def __init__(self, name, tomato_price):
        self.name = name
        self.tomato_price = tomato_price

    def sell(self, user):
        user.money -= int(self.tomato_price * (1 - user.discount))

my_market = Market("이마트", 3000)

class User1:
    nest_egg = 10000

    def __init__(self, name, money, discount):
        self.name = name
        self.money = money
        self.discount = discount / 100

    @classmethod
    def my_nest_egg(cls):
        print(f"비상금: {cls.nest_egg}")

hong = User1("홍길동", 10000, 5)

my_market.sell(hong)

print(hong.money)

User1.my_nest_egg()