# -*- coding: utf-8 -*-
"""1. 마크다운(markdown).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZFcY8oY_0TVVg-5lJCAa99D4LkxpnFld

#마크다운(Markdown)
    - 일반 텍스트 기반의 경략 마크업 언어로 웹 표준이 아닌 언어이다.
    마크업 언어란, 태그 등을 이용하여 문서나 데이터의 구조 등을 기술하며, 텍스트 만으로 서식이 있는 문서들을 작성할 때 자주 사용한다.
    간단한 HTML 드으이 서식 문서들을 작성할 때 자주 사용한다.

# 목차(header)
# : h1
## : h2
### : h3
#### : h4
##### : h5
###### : h6

## 리스트(List)
1. 장점
    - 간편하고 쉽다.
    - 다양한 플랫폼에서 지원한다.
2. 단점
    - 표준이 아니다.
    - 표현매체마다 다르게 보인다.
    - 모든 HTML을 대체하지 못하는 단점을 가진다.

<br />: 줄바꿈(line break)
- 파이썬은 1989년 12월 네덜란드 컴퓨터 과학자 <br /> 귀도 반 로섬이 개발하였다.

*내용* : 글자 기울이기(italic)
- 파이썬은 귀도 반 로섬이 *좋아하는 코미디언의 이름*을 따서 만든 이름이다.

**내용**: 글자를 굵게(bold)
- 파이썬의 로고는 **그리스 로마 신화의 뱀**을 의미하여 생긴 로고이다.

~~내용~~: 취소선(line through)
- ~~C언어~~로 2년 걸린 프로젝트를 파이썬으로 한 달만에 마무리했다.

<sup>내용</sup>: 위 첨자
- o(nlog<sup>2</sup>)

<sub>내용</sub>: 아래 첨자
- o(nlog<sub>2</sub>)

`내용`: 강조(back tick)
- `내용을 강조해보자!😺😸`

[] : 대괄호(브레이킷)<br />
{} : 중괄호(컬리 브레이스)<br />
() : 소괄호<br />

## 링크
- [구글](주소)
- [구글](https://www.google.com)

## 이미지
- ![고양이](이미지 주소)
- ![고양이](https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcR1C0XX0G2NSOp5mmXPK6gwcRaZdCdmm3AQopYkwtzWCqfsv_VN06S8YeJZKyT7CnEmqo286gVeCHSUI2T3h7Z3zA)

- <img src='https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcR1C0XX0G2NSOp5mmXPK6gwcRaZdCdmm3AQopYkwtzWCqfsv_VN06S8YeJZKyT7CnEmqo286gVeCHSUI2T3h7Z3zA' width='200' />

## 테이블(table)

|번호|이름|내용|
|----|----|----|
|001|홍길동|A|
|002|장보고|B|
|003|이순신|C|

## 리스트(list)
1. 목록의 구분
    1. 순서가 있는 목록(ordered list)
    2. 순서가 없는 목록(unordered list)

---

- 순서가 없는 목록
    - 들여쓰기로 하위 목록을 구분지을 수 있다.
    + 각 기호에 따라 표현되는 것이 다르지 않다.
    * (-, *, +) 기호를 자유롭게 사용할 수 있다.
"""