# -*- coding: utf-8 -*-
"""2. 출력함수(print).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i2r4I5JUmnHUqOXkhnodvT9f2eho8Djw
"""

# Ctrl + Enter
print("hello,World😺")
print("제 이름은 \n박세현 입니다.")
print(100)

# 함수: 이름 뒤에 소괄호
print("저의 이름은 \"박세현\" 이고, 나이는\"17\"살 입니다.")

"""## 제어문자
    - 반드시 따옴표 안에서 작성해야 한다.
    - 문자열 내부에서 기호를 문자열로 인식시키거나, 어떠한 기능을 수행하는 역할을 한다.

### \n
    - new line, 개행 문자, 줄바꿈

### \t
    - tab, 위 아래 줄 간격 맞춰 띄기

### \"
    - "를 표현한것

### \'
    - '를 표현한것

### \\
    - \를 표현한것

### 문자열('', "")
    - 컴퓨터가 명령어가 아닌 문자열 값 임을 구분할 수 있게 사용한다.
    즉, 문자열은 문자들의 나열이다.



"""

print("문자열을 그대로 사용하면, 명령어로 인식하여 오류를 발생시킨다.")