# -*- coding: utf-8 -*-
"""3. 주석(Comment).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H9quTjuqa76am5o8e4xzvvyUPsoq5ycr
"""

# "주석을 달아 보자!"
# "."

"""# 주석
    - 문장의 뜻을 쉽게 풀이해 놓은 설명문이다.
    따라서 프로그램 수행에는 전혀 영향을 미치지 않는다.

## 주석의 용도
    1) 프로그램의 개요를 소스 코드에 적을 때
    2) 어떤 변수나 로직에 설명이 필요할 때
    3) 이미 작성한 부분을 실행 시에 임시로 빼고 싶을 때

## 여러줄 주석(Doc String) : ''' ''', ''' '''
    - 본래 용도는 묘듈, 함수, 클래스 또는 메소드 정의의 첫 번째 명령문으로 발생하는 문자열을 리턴


"""