# -*- coding: utf-8 -*-
"""4. 변수(저장공간).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oH-W8Ih03k_4nqyVzGTcg1quiW71Xd3T
"""

name = "홍길동"
subject = "파이썬"

print(name)
print(subject)

print("저는 " + name + "이고 ",subject," 과목을 듣고 있습니다.")

# 실습1 : 이름, 나이, 취미를 입력 후 변수에 담는다.
# 그리고 아래와 같이 출력한다.
# ex) 저의 이름은 ooo이고, 나이는 oo살, 취미는 ooo입니다.

name = "홍길동"
name = "가나다"
name = "홍길동"
name = "나다라"
name = "홍길동"
name = "장보고"
age = 20
hobby = "운동"

print("저의 이름은 " + name + "이고, 나이는 " + str(age) + "살, 취미는 " + hobby + "입니다.")

num1 = 100
num2 = 300

print (num1 + num2)

# my_age = 100
# hobby3 = '공놀이'
# 3hobby3 = '공놀이'
# company_salary = 1000000000

# 키워드를 사용할 수 가 없다.
# print = 10
# if

print("출력해주세요~!")

# 자료형을 지켜야 한다.
# print(17 + "살")