# -*- coding: utf-8 -*-
"""5. 기본 자료형(Type).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YIJzgVFfn0TjQxPKqc1c6v-Xc_n2UaOL

# 기본 자료형(Data Type)
| 자료형 | 이름 | 값 |
| ----- | ----- | -----|
| 숫자 자료형 | int | 양의 정수, 음의 정수, 0, 1, 100, ... |
| 숫자 자료형 | float | 소수점이 있는 수, 0.0, 3.14, ... |
| 논리 자료형 | bool | 참 또는 거짓, Ture, False, 값이 있을 때 |
| 문자열 자료형 | str | 문자열, '', "", ... |
"""

# 정수형(int)
# int() : 숫자로 바뀔 수 있는 값을 int로 바꿔주는 함수

num1 = 3
num2 = int(2.7)
num3 = int("100")
# type() : 타입을 알려주는 함수
print(num1, type(num1))
print(num2, type(num2))
print(num3, type(num3))

# float() : 실수로 변환시켜주는 함수
num4 = 30
print(float(num4))
print(float("31.31"))

# 논리형 : True, False
# bool() : 논리형으로 바꿔주는 함수
data1 = True
data2 = False

print(data1, type(data1))

data3 = bool(100)
data4 = bool("ㄱ")
data5 = bool(3.14)

data6 = bool(0)
data7 = bool("")
data8 = bool(0.0)

print(data3, data4, data5)
print(data6, data7, data8)

# number
number = 10

# 2진수
print(bin(number), number)

# 8진수
print(oct(number), number)

# 16진수
print(hex(number), number)

# str() : 문자열로 변경해주는 함수
# window + . : 이모지
hello = 'Hello, Python!😺'

print(hello, type(hello))

# 인덱싱
print(hello[7])

# 느낌표 인덱싱
print(hello[13])
print(hello[-2])

# 문자열 슬라이싱
# : 클론
print(hello[7:12]) # 마지막을 포함하지 않는다.
print(hello[7:13])

num = "123456789"
# [시작인덱스:종료인덱스:스텝]
print(num[1::2])

#응용
# num를 반대로 출력하기
# ex) 987654321

print(num[len(num)::-1])

print(len(num))