# -*- coding: utf-8 -*-
"""7.  연산자(operator).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vvugHqey_IGNS1X34nOUwmifSIiSER73
"""

print(15 % 4) # 나머지 3
print(20 // 3) # 몫 6

# 내가 가진 돈
money = 1000000

# 노트북 구매
notebook = 100000

money = money - notebook

# 누적복합연산자
money -= notebook

print(money)

# 1. 사용자에게 최초 금액을 입력받기
message = '잔고를 입력하세요\n'
money = int(input(message))
# 2. 일을 해서 번 돈을 여러분의 지갑에 누적복합 연산자로 반영시키기
work = 100000
money += work

# 3. 폰을 구매했습니다. 폰을 구매한 가격만큼 누적복합 연산자로 반영시키기
phone = 30000
money -= phone

# 4. 최종 금액을 출력하기 (f-string)
# ex) 저의 지갑의 잔고는 oooo원입니다.
print(f'저의 지갑의 잔고는 {money}원 입니다.')

print(3 << 2)
print(60 >> 1)