# -*- coding: utf-8 -*-
"""9. 제어문(control statement).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lewWv0ilp7cFXBjX0enIrMmNySqi5xQW

#제어문
1. if문
    - 특정 조건의 만족 여부에 따라 실행
    - if, if else, if else else

     - if 조건식1 :
        - 조건식1을 만족하면 실행할 문장
     - elif 조건식2 :
        - 조건식 1을 만족하지 않고,
        - 조건식 2를 만족하면 실행할 문장
     - elif 조건식3 :
        - ...
     - else :
        - 모든 조건식을 만족하지 않을 때 실행할 문장
    
2. while문
    - 특정 조건을 만족하는 동안(true) 반복해서 수행한다
        - while 조건식 :
            반복할 문장
"""

# 시험
# 90점 이상 A, 80점 이상 B, 70점 이상 C, 70점 미만이면 F학점
grade = "";
score = int(input("점수를 입력하세요 : "))

# depth : 영역
if score >= 90 :
    grade = "A"
elif score >= 80 :
    grade = "B"
elif score >= 70 :
    grade = "C"
else :
    grade = "F"
print(grade)

# 실습 1.
# 사용자에게 두개의 정수를 입력 받아서,
# 두 수 중 큰 값을 비교하기
# if~elif~else문 사용
max = 0
num1 = int(input("정수1 : "))
num2 = int(input("정수2 : "))

if num1 > num2 :
    max = num1
elif num1 < num2 :
    max = num2
else :
    max = num1

print(f"큰 값은 {max}입니다.")

hangles = "가나다라마바사아자차카타파하"

# for hangle in '가나다라마바사아자차카타파하':
#     print(hangle)

for hangle in hangles :
    print(hangle)

food_list = ['치킨', '밥', '보쌈', '무뼈닭발', '햄버거', '떡볶이', '순대']
food_sets = {'치킨', '밥', '보쌈', '무뼈닭발', '햄버거', '떡볶이', '순대'}
sport_dict = {"축구": 11, "농구": 5, "배구": 7, "야구": 9, "배드민턴": 2}

for food in food_list :
    print(food)

print("====================================")

for food in food_sets :
    print(food)

print("====================================")
# 딕셔너리는 key값을 들고온다.
for sport in sport_dict :
    print(sport.upper(), sport_dict[sport])

# 종료값을 포함하지 않는다.
# range(시작값, 종료값, 스탭)
# for i in range(1,100) :
#     print(i)

# 짝수
for i in range(0, 100, 2):
    print(i)

# 홀수
for i in range(1, 100, 2):
    print(i)

# 실습 구구단 만들기
# for문 3단
# 출력 예시)
# 3 X 1 = 3
# 3 X 2 = 6

for i in range(1, 10):
    print(f"3 X {i} = {i*3}")

# 구구단 만들기
for i in range(1, 10):
    for j in range(1,10):
        print(f"{i} X {j} = {i*j}")

# break
for i in range(1, 5):
    print(i)
    if i == 2:
        break

print("탈출!😺")

# continue

for i in range(1, 5):
    if i == 2:
        continue
    print(i)

print("탈출!😺")

# pass
for i in range(1, 5):
    pass

print("탈출!😺")

# 예제
# 1) 1~100까지 홀수만 출력하기
# for i in range(1, 100, 2):
#     print(i)

# 2) 3~50까지 4씩 증가하는 반복문
for i in range(3, 50, 4):
    print(i)

# 3) food_list 중 '햄버거'만 출력하기
for food in food_list :
    if food == '햄버거':
        print(food)

# 4) food_list의 결과를 "오늘 저녁: ooo" 으로 모든 리스트를 출력하기\
for food in food_list :
    print(f"오늘 저녁: {food}")

# 5) 1~50까지 반복 후 3의 배수만 출력하기
for i in range(1, 50):
    if i % 3 == 0:
        print(i)

# 6) 1~50까지 반복 후 10~20만 출력하기
for i in range(1,51):
    if i == 10 or i == 20 :
        print(i)

print('a', end='')
print('b', end='')
print()
# 이중 for문
# 별 찍기 문제
#     *
#    ***
#   *****
#  *******
# *********

for i in range(1, 6):
    for j in range(5 - i, 0, -1):
        print(' ', end='')
    for j in range(1, 2*i):
        print('*', end='')
    print()

for i in range(1, 6):
    print(' '*(5-i) + '*'*(2*i-1))