# -*- coding: utf-8 -*-
"""1. 공공데이터 불러오기.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LtcwdFGeTVs0-TOOq2_NazNsZbPj_MQT
"""

import gdown
gdown.download('https://bit.ly/3eecMKZ',
               '남산도서관 장서 대출목록 (2021년 04월).csv',quiet=False)

"""gdown: 구글 드라이브 다운패키지
open: csv 파일 출력

"""

with open('남산도서관 장서 대출목록 (2021년 04월).csv') as f:
  print(f.readline())

"""유니코드 에러 한글형식 파일은 Utf-8이 아닌 EUC-kr임"""

import chardet
with open('남산도서관 장서 대출목록 (2021년 04월).csv', mode='rb') as f:
  d = f.readline()
print(chardet.detect(d))

with open('남산도서관 장서 대출목록 (2021년 04월).csv', encoding='EUC-KR') as f:
  print(f.readline())
  print(f.readline())

import pandas as pd
df = pd.read_csv('남산도서관 장서 대출목록 (2021년 04월).csv', encoding='EUC-KR')

df = pd.read_csv('남산도서관 장서 대출목록 (2021년 04월).csv', encoding='EUC-KR',
                low_memory=False)

"""저장

"""

df.to_csv('ns_202104.csv')

with open('ns_202104.csv') as f:
  for i in range(3):
    print(f.readline(), end='')

df = pd.read_csv('남산도서관 장서 대출목록 (2021년 04월).csv', encoding='euc-kr',
                 dtype={'ISBN': str, '세트 ISBN': str, '주제분류번호': str})

df.head()