# -*- coding: utf-8 -*-
"""02데이터 도식화.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VdJn3sRrLHBCFve5dQeJrJ3XHgnyLoyL
"""

d = {"name": "혼자 공부하는 데이터 분석"}
print(d['name'])

import json

d_str = json.dumps(d, ensure_ascii=False)
print(d_str)

print(type(d_str))

d2 = json.loads(d_str)
print(d2['name'])

print(type(d2))

d3 = json.loads('{"name": "혼자 공부하는 데이터 분석", "author": "박해선", "year": 2022}')
print(d3['name'])
print(d3['author'])
print(d3['year'])

d3 = json.loads('{"name": "혼자 공부하는 데이터 분석", "author": ["박해선","홍길동"], "year": 2022}')
print(d3['author'][1])

d4_str = """
[
  {"name": "혼자 공부하는 데이터 분석", "author": "박해선", "year": 2022},
  {"name": "혼자 공부하는 머신러인+딥러닝", "author": "박해선", "year": 2020}
]
"""

d4 = json.loads(d4_str)
print(d4[0]['name'])

import pandas as pd
pd.read_json(d4_str)

pd.DataFrame(d4)

x_str = """
<book>
  <name>혼자 공부하는 데이터 분석</name>
  <author>박해선</author>
  <year>2022</year>
</book>
"""

import xml.etree.ElementTree as et
book = et.fromstring(x_str)

print(type(book))

print(book.tag)

book_childs = list(book)
print(book_childs)

name, author, year = book_childs
print(name.text)
print(author.text)
print(year.text)

name = book.findtext('name')
author = book.findtext('author')
year = book.findtext('year')
print(name)
print(author)
print(year)

x2_str = """
<books>
  <book>
    <name>혼자 공부하는 데이터 분석</name>
    <author>박해선</author>
    <year>2022</year>
  </book>
  <book>
    <name>혼자 공부하는 머신러닝+딥러닝</name>
    <author>박해선</author>
    <year>2020</year>
  </book>
</books>
"""

books = et.fromstring(x2_str)
print(books.tag)

for book in books.findall('book'):
    name = book.findtext('name')
    author = book.findtext('author')
    year = book.findtext('year')
    print(name)
    print(author)
    print(year)
    print()

pd.read_xml(x2_str)

"""---------------------------------------3-25수업------------------------------"""

import gdown
gdown.download('https://bit.ly/3q9SZix', '20s_best_book.json',
               quiet=False)

import pandas as pd
books_df = pd.read_json('20s_best_book.json')
books_df.head()

books_df.loc[[0,1], ['bookname','authors']]

books_df.loc[0:1, 'bookname':'authors']

books = books_df.loc[:, 'no':'isbn13']
books.head()

import requests
isbn