# -*- coding: utf-8 -*-
"""3-2. 잘못된 데이터 수정하기.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V-_LfwmYkPKWj9HS8QfmLhu7-i2BZV-R
"""

import gdown
gdown.download('https://bit.ly/3GisL6J','ns_book4.csv', quiet=False)

import pandas as pd
ns_book4 = pd.read_csv('ns_book4.csv', low_memory=False)
ns_book4.head()

ns_book4.info()

ns_book4.isna().sum()

ns_book4.loc[0, '도서권수'] = None
ns_book4['도서권수'].isna().sum()

ns_book4.head(2)

ns_book4.loc[0, '도서권수'] = 1
ns_book4 = ns_book4.astype({'도서권수': 'int32', '대출건수': 'int32'})
ns_book4.head(2)

ns_book4.loc[0, '부가기호'] = None
ns_book4.head(2)

import numpy as np
ns_book4.loc[0, '부가기호'] = np.nan
ns_book4.head(2)

set_isbn_na_rows = ns_book4['세트 ISBN'].isna()

ns_book4.loc[set_isbn_na_rows, '세트 ISBN'] = ''
ns_book4['세트 ISBN'].isna().sum()

ns_book4.fillna('없음').isna().sum()

ns_book4['부가기호'].fillna('없음').isna().sum()

ns_book4.fillna({'부가기호': '없음'}).isna().sum()

ns_book4.replace(np.nan, '없음').isna().sum()

ns_book4.replace([np.nan, '2021'], ['없음', '21']).head(2)

ns_book4.replace({np.nan: '없음', '2021': '21'}).head(2)

ns_book4.replace({'부가기호': np.nan}, '없음').head(2)

ns_book4.replace({'부가기호': {np.nan: '없음'}, '발행년도': {'2021': '21'}}).head(2)

ns_book4.replace({'발행년도': {'2021': '21'}})[100:102]

ns_book4.replace({'발행년도': {r'\d\d(\d\d)': r'\1'}}, regex=True)[100:102]

ns_book4.replace({'발행년도': {r'\d{2}(\d{2})': r'\1'}}, regex=True)[100:102]

ns_book4.replace({'저자': {r'(.*)\s\(지은이\)(.*)\s\(옮긴이\)': r'\1\2'}, '발행년도': {r'\d{2}(\d{2})': r'\1'}}, regex=True)[100:102]

ns_book4.astype({'발행년도': 'int32'})

ns_book4['발행년도'].str.contains('1988').sum()

invalid_number = ns_book4['발행년도'].str.contains('\D', na=True)
print(invalid_number.sum())
ns_book4[invalid_number].head()

ns_book5 = ns_book4.replace({'발행년도':r'.*(\d{4}).*'}, r'\1', regex=True)
ns_book5[invalid_number].head()

unknown_year = ns_book5['발행년도'].str.contains('\D', na=True)
print(unknown_year.sum())
ns_book5[unknown_year].head()

ns_book5.loc[unknown_year, '발행년도'] = '-1'
ns_book5 = ns_book5.astype({'발행년도': 'int32'})

(ns_book5['발행년도'] > 4000).sum()

dangun_yy_rows = ns_book5['발행년도'].gt(4000)
ns_book5.loc[dangun_yy_rows, '발행년도'] = ns_book5.loc[dangun_yy_rows, '발행년도'] - 2333
dangun_year = (ns_book5['발행년도'] > 4000)
print(dangun_year.sum())
ns_book5[dangun_year].head(2)

ns_book5.loc[dangun_year, '발행년도'] = -1

old_books = ns_book5['발행년도'].gt(0) & ns_book5['발행년도'].lt(1900)
ns_book5[old_books]

ns_book5.loc[old_books, '발행년도'] = -1
ns_book5['발행년도'].eq(-1).sum()

ns_book5.head()