# -*- coding: utf-8 -*-
"""4-1.통계로 요약하기.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19tXt6cTk2QESDpeMv4G0YbSFAP_BYqjx
"""

import gdown
gdown.download('https://bit.ly/3736JW1', 'ns_book6.csv', quiet=False)

import pandas as pd
ns_book6 = pd.read_csv('ns_book6.csv', low_memory=False)
ns_book6.head()

ns_book6.describe()

sum(ns_book6['도서권수']==0)

ns_book7 = ns_book6[ns_book6['도서권수']>0]

ns_book7.describe(percentiles=[0.3, 0.6, 0.9])

ns_book7.describe(include='object')

x = [10, 20, 30]
sum = 0
for i in range(3):
  sum += x[i]
print("평균:", sum / len(x))

ns_book7['대출건수'].mean()

ns_book7['대출건수'].median()

temp_df = pd.DataFrame([1,2,3,4])
temp_df.median()

ns_book7['대출건수'].drop_duplicates().median()

ns_book7['대출건수'].min()

ns_book7['대출건수'].max()

ns_book7['대출건수'].quantile(0.25)

ns_book7['대출건수'].quantile([0.25,0.5,0.75])

pd.Series([1,2,3,4,5]).quantile(0.9)

borrow_10_flag = ns_book7['대출건수'] < 10

borrow_10_flag.mean()

ns_book7['대출건수'].quantile(0.65)

ns_book7['대출건수'].var()

ns_book7['대출건수'].std()

ns_book7['도서명'].mode()

ns_book7['발행년도'].mode()

