# -*- coding: utf-8 -*-
"""4-2.분포 요약하기

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wxWQRPvq7F1gGKJ1PPAkCVTRwFqQl_3b
"""

import gdown
gdown.download('https://bit.ly/3pK7iuu', 'ns_book7.csv', quiet=False)

import pandas as pd
ns_book7 = pd.read_csv('ns_book7.csv', low_memory = False)
ns_book7.head()

import matplotlib.pyplot as plt

plt.scatter([1,2,3,4],[1,2,3,4])

plt.scatter(ns_book7['번호'],ns_book7['대출건수'])
plt.show()

plt.scatter(ns_book7['도서권수'], ns_book7['대출건수'])
plt.show()

plt.scatter(ns_book7['도서권수'], ns_book7['대출건수'], alpha=0.1)
plt.show()

average_borrows = ns_book7['대출건수']/ns_book7['도서권수']
plt.scatter(average_borrows, ns_book7['대출건수'], alpha=0.1)
plt.show()

plt.hist([0,3,5,6,7,7,8,13], bins=5)
plt.show()

import numpy as np
np.histogram_bin_edges([0,3,5,6,7,7,9,13], bins=5)

np.random.seed(42)
random_samples = np.random.randn(1000)

print(np.mean(random_samples), np.std(random_samples))

plt.hist(random_samples)
plt.show()

plt.hist(ns_book7['대출건수'])
plt.show()

plt.hist(ns_book7['대출건수'])
plt.yscale('log')
plt.show()

plt.hist(ns_book7['대출건수'], bins=100)
plt.yscale('log')
plt.show()

title_len = ns_book7['도서명'].apply(len)
plt.hist(title_len, bins=100)
plt.show()

plt.hist(title_len, bins=100)
plt.xscale('log')
plt.show()

plt.boxplot(ns_book7[['대출건수','도서권수']])
plt.show()

plt.boxplot(ns_book7[['대출건수','도서권수']])
plt.yscale('log')
plt.show()

plt.boxplot(ns_book7[['대출건수','도서권수']], vert=False)
plt.yscale('log')
plt.show()

plt.boxplot(ns_book7[['대출건수','도서권수']], whis=10)
plt.yscale('log')
plt.show()

plt.boxplot(ns_book7[['대출건수','도서권수']], whis=(0,100))
plt.yscale('log')
plt.show()